site_name: Semblage Documentation

nav:
    - Home: index.md
    - Introduction: introduction.md
    - Installation: installation.md
    - Usage: usage.md
    - Tutorials: tutorials/index.md
    - Community: community.md
    - Roadmap: roadmap.md