extends Node

class_name ToolTips

const selected_lang = "english"

const tool_tips_english = {
	arc_angle_1_ctrl_hint_tooltip = "Start angle of the arc.",
	arc_angle_2_ctrl_hint_tooltip = "End angle of the arc. If angle2 and angle1 are the same,\na closed ellipse is the result, which is the default.",
	arc_make_wire_ctrl_hint_tooltip = "Convert the resulting arc edge to a wire.",
	arc_rotation_angle_ctrl_hint_tooltip = "Angle to rotate the created ellipse/arc by.",
	arc_sense_ctrl_hint_tooltip = "Clockwise (-1) or counter clockwise (1).",
	arc_start_at_current_ctrl_hint_tooltip = "If checked, the start point of arc is moved to current point.\nIf unchecked, the center of arc is on current point.",
	arc_x_radius_ctrl_hint_tooltip = "X radius of the ellipse (along the x-axis of plane\nthe ellipse should lie in).",
	arc_y_radius_ctrl_hint_tooltip = "Y radius of the ellipse (along the y-axis of plane\nthe ellipse should lie in).",
	box_length_ctrl_hint_tooltip = "Box size in X direction.",
	box_width_ctrl_hint_tooltip = "Box size in Y direction.",
	box_height_ctrl_hint_tooltip = "Box size in Z direction.",
	blind_cut_distance_ctrl_hint_tooltip = "Distance to extrude before cutting (> 0.0 means in the positive direction of the workplane normal, < 0.0 means in the negative direction).",
	cbore_cbore_dia_ctrl_hint_tooltip = "Diameter of the counter-bore hole. This diameter\nshould be larger than that of the main hole.",
	cbore_cbore_depth_ctrl_hint_tooltip = "Depth of the counter-bore hole. This depth should be\nless than that of the main hole.",
	cen_x_ctrl_hint_tooltip = "If checked, will be centered around the X axis reference point.\nIf unchecked, the corner will be on the reference point and it\nwill extend in the positive x direction.",
	cen_y_ctrl_hint_tooltip = "If checked, will be centered around the Y axis reference point.\nIf unchecked, the corner will be on the reference point and it\nwill extend in the positive y direction.",
	cen_z_ctrl_hint_tooltip = "If checked, will be centered around the Z axis reference point.\nIf unchecked, the corner will be on the reference point and it\nwill extend in the positive z direction.",
	center_x_coord_ctrl_hint_tooltip = "Shift local X coordinate to the specified location. Used to adjust the\ncenter point after it has been created automatically on a face, but is\nnot where it needs to be.",
	center_y_coord_ctrl_hint_tooltip = "Shift local Y coordinate to the specified location. Used to adjust the\ncenter point after it has been created automatically on a face, but is\nnot where it needs to be.",
	chamfer_length_ctrl_hint_tooltip = "Length of the chamfer. Must be > 0.",
	chamfer_asym_length_ctrl_hint_tooltip = "Can be set to > 0 for an asymmetrical chamfer.",
	combine_ctrl_hint_tooltip = "Whether this should be combined with other solids on the stack.",
	clean_ctrl_hint_tooltip = "Whether to clean the resulting geometry. If the CAD kernel\nis yielding invalid results, try disabling this.",
	csink_angle_ctrl_hint_tooltip = "Angle of the countersink in degrees (82 is common).",
	csink_dia_ctrl_hint_tooltip = "Largest diameter of the counter-sink. This diameter\nshould be larger than that of the main hole.",
	extrude_both_ctrl_hint_tooltip = "Extrude in both directions symmetrically.",
	extrude_distance_ctrl_hint_tooltip = "Distance to extrude along the normal of the workplane.",
	fillet_radius_ctrl_hint_tooltip = "Radius of the fillet, must be > zero.",
	for_construction_ctrl_hint_tooltip = "Whether the new wires should be reference geometry only. Check if the\nwires are for reference, uncheck if they are creating part geometry.",
	hline_dist_ctrl_hint_tooltip = "X distance from current point.",
	hlineto_x_coord_ctrl_hint_tooltip = "X coordinate for the end of the line.",
	hole_dia_ctrl_hint_tooltip = "Diameter of the main hole.",
	hole_depth_ctrl_hint_tooltip = "Depth of the main hole. Setting to 0 causes it to go all\nthe way through the object it is being placed in.",
	invert_ctrl_hint_tooltip = "Flip the normal for the operation to the opposite direction.",
	line_x_dist_ctrl_hint_tooltip = "X distance from the current point.",
	line_y_dist_ctrl_hint_tooltip = "Y distance from the current point.",
	lineto_x_dist_ctrl_hint_tooltip = "The X point in workplane plane coordinates.",
	lineto_y_dist_ctrl_hint_tooltip = "The Y point in workplane plane coordinates.",
	move_x_dist_ctrl_hint_tooltip = "Desired X distance in local coordinates.",
	move_y_dist_ctrl_hint_tooltip = "Desired Y distance in local coordinates.",
	moveto_x_dist_ctrl_hint_tooltip = "Desired X location in local coordinates.",
	moveto_y_dist_ctrl_hint_tooltip = "Desired Y location in local coordinates.",
	offset2d_thickness_ctrl_hint_tooltip = "Offset thickness. Negative thickness denotes offset to inside.",
	offset2d_kind_ctrl_hint_tooltip = "Use 'arc' for rounded corners, and 'intersection' for sharp corners.",
	polar_array_angle_ctrl_hint_tooltip = "The angle (degrees) to fill with elements. A positive value will\nfill in the counter-clockwise direction. If fill is false, angle is\nthe angle between elements.",
	polar_array_count_ctrl_hint_tooltip = "Number of elements in the array (must be > 0).",
	polar_array_fill_ctrl_hint_tooltip = "Interpret the angle as total if checked.",
	polar_array_radius_ctrl_hint_tooltip = "Distance away from the center that\nthe array objects will be placed.",
	polar_array_rotate_ctrl_hint_tooltip = "Rotate every item to be oriented with respect\nto the center of the array.",
	polar_array_start_angle_ctrl_hint_tooltip = "Starting angle (degrees) of array. 0 degrees is situated along local X-axis.",
	polar_line_distance_ctrl_hint_tooltip = "Distance of the end of the line from the current point.",
	polar_line_angle_ctrl_hint_tooltip = "Angle of the vector to the end of the line with respect\nto the X-axis.",
	polar_line_to_distance_ctrl_hint_tooltip = "Distance of the end of the line from the origin.",
	polygon_dia_ctrl_hint_tooltip = "Size of the circle the polygon is inscribed into.",
	polygon_nsides_ctrl_hint_tooltip = "Number of sides, must be > 3.",
	polyline_tuple_x_ctrl_hint_tooltip = "X point coordinate in workplane coordinates.",
	polyline_tuple_y_ctrl_hint_tooltip = "Y point coordinate in workplane coordinates.",
	push_points_point_lr_ctrl_hint_tooltip = "X coordinate of point to push onto the stack.",
	push_points_point_tb_ctrl_hint_tooltip = "Y coordinate of point to push onto the stack.",
	radius_arc_end_point_x_ctrl_hint_tooltip = "X coordinate of the end point for the arc.",
	radius_arc_end_point_y_ctrl_hint_tooltip = "Y coordinate of the end point for the arc.",
	radius_arc_radius_ctrl_hint_tooltip = "Radius of the arc between start point and end point.",
	radius_ctrl_hint_tooltip = "Radius of the circle.",
	rarray_x_count_ctrl_hint_tooltip = "Number of X points (must be > 0).",
	rarray_y_count_ctrl_hint_tooltip = "Number of Y points (must be > 0).",
	rarray_x_spacing_ctrl_hint_tooltip = "Spacing between points in the x direction ( must be > 0).",
	rarray_y_spacing_ctrl_hint_tooltip = "Spacing between points in the y direction ( must be > 0).",
	rect_x_length_ctrl_hint_tooltip = "Length in X direction (in workplane coordinates).",
	rect_y_length_ctrl_hint_tooltip = "Length in Y direction (in workplane coordinates).",
	rect_centered_ctrl_hint_tooltip = "If checked, the rectangle will be centered around the reference point.\nIf unchecked, the corner of the rectangle will be on the reference point\nand it will extend in the positive x and y directions.",
	revolve_angle_ctrl_hint_tooltip = "Angle to revolve through. Anything less than 360 degrees will leave the shape open.",
	revolve_axis_start_x_ctrl_hint_tooltip = "X start point of the axis of rotation.",
	revolve_axis_start_y_ctrl_hint_tooltip = "Y start point of the axis of rotation.",
	revolve_axis_start_z_ctrl_hint_tooltip = "Z start point of the axis of rotation.",
	revolve_axis_end_x_ctrl_hint_tooltip = "X end point of the axis of rotation.",
	revolve_axis_end_y_ctrl_hint_tooltip = "Y end point of the axis of rotation.",
	revolve_axis_end_z_ctrl_hint_tooltip = "Z end point of the axis of rotation.",
	rotate_axis_start_x_ctrl_hint_tooltip = "X point of the first axis of rotation.",
	rotate_axis_start_y_ctrl_hint_tooltip = "Y point of the first axis of rotation.",
	rotate_axis_start_z_ctrl_hint_tooltip = "Z point of the first axis of rotation.",
	rotate_about_center_axis_end_x_ctrl_hint_tooltip = "X point of the second axis of rotation.",
	rotate_about_center_axis_end_y_ctrl_hint_tooltip = "Y point of the second axis of rotation.",
	rotate_about_center_axis_end_z_ctrl_hint_tooltip = "Z point of the second axis of rotation.",
	rotate_angle_ctrl_hint_tooltip = "Rotation angle in degrees.",
	sagitta_arc_end_point_x_ctrl_hint_tooltip = "X end point for the arc.",
	sagitta_arc_end_point_y_ctrl_hint_tooltip = "Y end point for the arc.",
	sagitta_arc_sag_ctrl = "Perpendicular distance from arc center to arc baseline.",
	taper_ctrl_hint_tooltip = "Angle for optional tapered extrusion.",
	wp_cen_ctrl_hint_tooltip = "How the local origin of the workplane is determined. CenterOfBoundBox chooses the\ncenter of the smallest box that the geometry will fit inside of. CenterOfMass is essentially\nthe center of gravity of the geometry, and varies dependeing on whether material is added\nor removed from an object, and whether that material is removed asymmetrically.\nProjectedOrigin projects the center of the old workplane onto the workplane that is being\ncreated."
}


static func get_tts():
	# Select the appropriate tool tips for the language
	if selected_lang == "english":
		return tool_tips_english
