name: export

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  export:
      runs-on: "ubuntu-latest"
      name: Export Semblage
      steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Project
        run: |
          sudo apt install -y wget
          curl https://downloads.tuxfamily.org/godotengine/3.3.2/Godot_v3.3.2-stable_linux_headless.64.zip --output Godot_v3.3.2-stable_linux_headless.64.zip
          unzip Godot_v3.3.2-stable_linux_headless.64.zip
          chmod +x Godot_v3.3.2-stable_linux_headless.64
          wget -O semblage_libs.tar.xz https://7bindustries.com/static/semblage_libs.tar.xz
          mv semblage_libs.tar.xz $PWD/lib/
          cd $PWD/lib/
          tar -xvf semblage_libs.tar.xz
          cd ..
          wget -O gut.tar.gz https://github.com/bitwes/Gut/archive/refs/tags/v7.1.0.tar.gz
          tar -xvf gut.tar.gz
          mv Gut-7.1.0/addons/gut addons/
          wget -O pythonscript.tar.bz2 https://github.com/touilleMan/godot-python/releases/download/v0.50.0/godot-python-0.50.0-x11-64.tar.bz2
          tar -xvf pythonscript.tar.bz2
          addons/pythonscript/x11-64/bin/python3.8 -m ensurepip
          addons/pythonscript/x11-64/bin/python3.8 -m pip install nptyping
          addons/pythonscript/x11-64/bin/python3.8 -m pip install scipy
      - name: Do Export
        uses: firebelley/godot-export@v2.8.0
        with:
          create_release: false
          archive_export_output: true
          base_version: 0.1.0
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.3/Godot_v3.3-stable_linux_headless.64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.3/Godot_v3.3-stable_export_templates.tpz
          godot_template_version: 3.3.stable
          relative_project_path: ./
        env:
          GITHUB_TOKEN: ${{ secrets.EXPORT_GITHUB_TOKEN }}
      - name: Clean Up Export
        run: |
          mkdir -p ~/.local/share/godot/dist/Semblage_Linux/Semblage_Linux
          cd ~/.local/share/godot/dist/Semblage_Linux/Semblage_Linux
          unzip ~/.local/share/godot/dist/LinuxX11.zip
          chmod +x Semblage
      - name: Upload Packages
        uses: actions/upload-artifact@v2
        with:
          name: Semblage_Linux_x86_64
          path: ~/.local/share/godot/dist/Semblage_Linux
