# This is a basic workflow to help you get started with Actions

name: tests

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      # - name: Run a one-line script
      # run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Install Godot and run GUT tests
        run: |
          sudo apt install -y wget
          pip install nptyping
          pip install scipy
          curl https://downloads.tuxfamily.org/godotengine/3.3.2/Godot_v3.3.2-stable_linux_headless.64.zip --output Godot_v3.3.2-stable_linux_headless.64.zip
          unzip Godot_v3.3.2-stable_linux_headless.64.zip
          chmod +x Godot_v3.3.2-stable_linux_headless.64
          wget -O semblage_libs.tar.xz https://7bindustries.com/static/semblage_libs.tar.xz
          mv semblage_libs.tar.xz $PWD/lib/
          cd $PWD/lib/
          tar -xvf semblage_libs.tar.xz
          cd ..
          wget -O gut.tar.gz https://github.com/bitwes/Gut/archive/refs/tags/v7.1.0.tar.gz
          tar -xvf gut.tar.gz
          mv Gut-7.1.0/addons/gut addons/
          wget -O pythonscript.tar.bz2 https://github.com/touilleMan/godot-python/releases/download/v0.50.0/godot-python-0.50.0-x11-64.tar.bz2
          tar -xvf pythonscript.tar.bz2
          export LD_LIBRARY_PATH=$PWD/lib
          LD_LIBRARY_PATH=$PWD/lib ./Godot_v3.3.2-stable_linux_headless.64 --verbose -d -s --path ./project addons/gut/gut_cmdln.gd -gdir=res://tests -ginclude_subdirs -gexit
